#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;

const MARK: &str = "# cc-manager-integration";
const KEYCHAIN_PREFIX: &str = "cc-manager";

#[derive(Serialize, Deserialize, Clone, Default)]
#[serde(rename_all = "camelCase")]
struct Profile {
    name: String,
    #[serde(rename = "type")]
    type_: String,
    #[serde(default)]
    base_url: String,
    #[serde(default)]
    token_enc: Option<String>,
    #[serde(default)]
    has_token: bool,
    #[serde(default)]
    share_skills: bool,
    #[serde(default)]
    share_plugins: bool,
    #[serde(default)]
    opus_model: String,
    #[serde(default)]
    sonnet_model: String,
    #[serde(default)]
    haiku_model: String,
}

#[derive(Serialize)]
struct EnvInfo {
    platform: String,
    claude_found: bool,
    integrated: bool,
    cert_imported: bool,
    cert_count: usize,
}

// ---------------- 路径 ----------------
fn home() -> PathBuf {
    dirs::home_dir().unwrap_or_else(|| PathBuf::from("."))
}
fn cfg_dir() -> PathBuf {
    home().join(".cc-manager")
}
fn cfg_path() -> PathBuf {
    cfg_dir().join("config.json")
}
fn cert_path() -> PathBuf {
    cfg_dir().join("ca-cert.pem")
}
fn sh_path() -> PathBuf {
    cfg_dir().join("cc.sh")
}
fn ps_path() -> PathBuf {
    cfg_dir().join("cc.ps1")
}

// ---------------- 配置读写 ----------------
fn load() -> Vec<Profile> {
    if let Ok(s) = fs::read_to_string(cfg_path()) {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&s) {
            if let Some(arr) = v.get("profiles") {
                if let Ok(list) = serde_json::from_value::<Vec<Profile>>(arr.clone()) {
                    return list;
                }
            }
        }
    }
    vec![]
}

fn save(list: &[Profile]) -> std::io::Result<()> {
    fs::create_dir_all(cfg_dir())?;
    let obj = serde_json::json!({ "profiles": list });
    fs::write(cfg_path(), serde_json::to_string_pretty(&obj)?)
}

// ---------------- shell 引用 ----------------
fn sh_q(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}
fn ps_q(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

// ---------------- 生成集成脚本 ----------------
fn generate_sh(list: &[Profile]) -> String {
    let mut o = String::from(
        "#!/bin/bash\n# Auto-generated by Claude Route Manager. Do not edit.\n",
    );
    o += "if [ -f \"$HOME/.cc-manager/ca-cert.pem\" ]; then export NODE_EXTRA_CA_CERTS=\"$HOME/.cc-manager/ca-cert.pem\"; fi\n";
    o += "claude() {\n  case \"$1\" in\n";
    for p in list {
        let n = &p.name;
        if n.is_empty() {
            continue;
        }
        o += &format!("    {n})\n");
        o += &format!(
            "      shift; _cch=\"$HOME/.claude-split/{n}\"; mkdir -p \"$_cch/.local/bin\"\n"
        );
        if p.type_ == "router" {
            let url = sh_q(&p.base_url);
            let svc = sh_q(&format!("{KEYCHAIN_PREFIX}:{n}"));
            let mut envs = format!(
                "HOME=\"$_cch\" ANTHROPIC_BASE_URL={url} ANTHROPIC_AUTH_TOKEN=\"$(security find-generic-password -s {svc} -w 2>/dev/null)\" CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1"
            );
            if !p.opus_model.is_empty() {
                envs += &format!(" ANTHROPIC_DEFAULT_OPUS_MODEL={}", sh_q(&p.opus_model));
            }
            if !p.sonnet_model.is_empty() {
                envs += &format!(" ANTHROPIC_DEFAULT_SONNET_MODEL={}", sh_q(&p.sonnet_model));
            }
            if !p.haiku_model.is_empty() {
                envs += &format!(" ANTHROPIC_DEFAULT_HAIKU_MODEL={}", sh_q(&p.haiku_model));
            }
            o += &format!("      {envs} command claude \"$@\" ;;\n");
        } else {
            o += "      HOME=\"$_cch\" command claude \"$@\" ;;\n";
        }
    }
    o += "    *) command claude \"$@\" ;;\n  esac\n}\n";
    o
}

fn generate_ps1(list: &[Profile]) -> String {
    let mut o = String::new();
    o += "# Auto-generated by Claude Route Manager. Do not edit.\n";
    o += "if (Test-Path \"$env:USERPROFILE\\.cc-manager\\ca-cert.pem\") { $env:NODE_EXTRA_CA_CERTS = \"$env:USERPROFILE\\.cc-manager\\ca-cert.pem\" }\n";
    o += "function claude {\n";
    o += "  param([Parameter(ValueFromRemainingArguments=$true)][string[]]$A)\n";
    o += "  $exe = $null\n";
    o += "  foreach ($cand in @('claude.cmd','claude.exe','claude.bat')) {\n";
    o += "    $c = Get-Command $cand -CommandType Application -ErrorAction SilentlyContinue | Select-Object -First 1\n";
    o += "    if ($c) { $exe = $c.Source; break }\n";
    o += "  }\n";
    o += "  if (-not $exe) { Write-Host 'claude not found in PATH'; return }\n";
    o += "  $sub = if ($A.Count -ge 1) { $A[0] } else { '' }\n";
    o += "  $rest = if ($A.Count -gt 1) { $A[1..($A.Count-1)] } else { @() }\n";
    o += "  switch ($sub) {\n";
    for p in list {
        let n = &p.name;
        if n.is_empty() {
            continue;
        }
        o += &format!("    {} {{\n", ps_q(n));
        o += &format!("      $h = Join-Path $env:USERPROFILE '.claude-split\\{n}'\n");
        o += "      New-Item -ItemType Directory -Force -Path (Join-Path $h '.local\\bin') | Out-Null\n";
        o += "      $bk=@{USERPROFILE=$env:USERPROFILE;ANTHROPIC_BASE_URL=$env:ANTHROPIC_BASE_URL;ANTHROPIC_AUTH_TOKEN=$env:ANTHROPIC_AUTH_TOKEN;ANTHROPIC_DEFAULT_OPUS_MODEL=$env:ANTHROPIC_DEFAULT_OPUS_MODEL;ANTHROPIC_DEFAULT_SONNET_MODEL=$env:ANTHROPIC_DEFAULT_SONNET_MODEL;ANTHROPIC_DEFAULT_HAIKU_MODEL=$env:ANTHROPIC_DEFAULT_HAIKU_MODEL;CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=$env:CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC}\n";
        o += "      try {\n";
        o += "        $env:USERPROFILE=$h\n";
        if p.type_ == "router" {
            o += &format!("        $env:ANTHROPIC_BASE_URL={}\n", ps_q(&p.base_url));
            o += "        $env:CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC='1'\n";
            if let Some(enc) = &p.token_enc {
                if !enc.is_empty() {
                    o += &format!("        $sec=ConvertTo-SecureString {}\n", ps_q(enc));
                    o += "        $b=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec)\n";
                    o += "        $env:ANTHROPIC_AUTH_TOKEN=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($b)\n";
                    o += "        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($b)\n";
                }
            }
            if !p.opus_model.is_empty() {
                o += &format!(
                    "        $env:ANTHROPIC_DEFAULT_OPUS_MODEL={}\n",
                    ps_q(&p.opus_model)
                );
            }
            if !p.sonnet_model.is_empty() {
                o += &format!(
                    "        $env:ANTHROPIC_DEFAULT_SONNET_MODEL={}\n",
                    ps_q(&p.sonnet_model)
                );
            }
            if !p.haiku_model.is_empty() {
                o += &format!(
                    "        $env:ANTHROPIC_DEFAULT_HAIKU_MODEL={}\n",
                    ps_q(&p.haiku_model)
                );
            }
        }
        o += "        & $exe @rest\n";
        o += "      } finally {\n";
        o += "        foreach ($k in $bk.Keys) { if ($bk[$k]) { Set-Item -Path \"Env:\\$k\" -Value $bk[$k] } else { Remove-Item -Path \"Env:\\$k\" -ErrorAction SilentlyContinue } }\n";
        o += "      }\n";
        o += "    }\n";
    }
    o += "    default { & $exe @A }\n";
    o += "  }\n}\n";
    o
}

fn ensure_line(path: &PathBuf, line: &str) -> std::io::Result<()> {
    let existing = fs::read_to_string(path).unwrap_or_default();
    if existing.contains(MARK) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        let _ = fs::create_dir_all(parent);
    }
    let sep = if existing.is_empty() || existing.ends_with('\n') {
        ""
    } else {
        "\n"
    };
    fs::write(path, format!("{existing}{sep}{line}\n"))
}

fn install_integration(list: &[Profile]) -> Result<String, String> {
    fs::create_dir_all(cfg_dir()).map_err(|e| e.to_string())?;
    if cfg!(target_os = "windows") {
        fs::write(ps_path(), generate_ps1(list)).map_err(|e| e.to_string())?;
        let out = ps_command()
            .args(["-NoProfile", "-Command", "$PROFILE"])
            .output()
            .map_err(|e| e.to_string())?;
        let profile_path = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if profile_path.is_empty() {
            return Ok("已生成 cc.ps1，但未能定位 PowerShell $PROFILE，请手动 dot-source 它。".into());
        }
        let line = format!(". \"{}\"  {}", ps_path().display(), MARK);
        ensure_line(&PathBuf::from(&profile_path), &line).map_err(|e| e.to_string())?;
        Ok("已接入 PowerShell $PROFILE。请新开一个 PowerShell 窗口生效。".into())
    } else {
        fs::write(sh_path(), generate_sh(list)).map_err(|e| e.to_string())?;
        let line = format!(
            "[ -f \"{p}\" ] && source \"{p}\"  {m}",
            p = sh_path().display(),
            m = MARK
        );
        let _ = ensure_line(&home().join(".zshrc"), &line);
        let _ = ensure_line(&home().join(".bashrc"), &line);
        Ok("已接入 shell 配置。请新开一个终端窗口（或 source 一下）生效。".into())
    }
}

// ---------------- token（平台原生） ----------------
// 在 Windows 上创建 PowerShell 命令时隐藏控制台窗口（CREATE_NO_WINDOW）
fn ps_command() -> std::process::Command {
    #[allow(unused_mut)]
    let mut c = std::process::Command::new("powershell");
    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        c.creation_flags(0x08000000);
    }
    c
}

fn store_token(name: &str, token: &str) -> Result<Option<String>, String> {
    if cfg!(target_os = "macos") {
        let svc = format!("{KEYCHAIN_PREFIX}:{name}");
        let user = std::env::var("USER").unwrap_or_else(|_| "user".into());
        let _ = std::process::Command::new("security")
            .args(["delete-generic-password", "-s", &svc])
            .output();
        let out = std::process::Command::new("security")
            .args([
                "add-generic-password", "-a", &user, "-s", &svc, "-w", token, "-U",
            ])
            .output()
            .map_err(|e| e.to_string())?;
        if !out.status.success() {
            return Err(String::from_utf8_lossy(&out.stderr).trim().to_string());
        }
        Ok(None)
    } else if cfg!(target_os = "windows") {
        // PowerShell 5.1 的 -Command 模式下 $args 不可靠，直接把 key 拼进脚本（单引号转义）
        let escaped = token.replace('\'', "''");
        let script = format!(
            "ConvertTo-SecureString -String '{escaped}' -AsPlainText -Force | ConvertFrom-SecureString"
        );
        let out = ps_command()
            .args(["-NoProfile", "-Command", &script])
            .output()
            .map_err(|e| e.to_string())?;
        let enc = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if enc.is_empty() {
            return Err(format!(
                "PowerShell 加密失败：{}",
                String::from_utf8_lossy(&out.stderr).trim()
            ));
        }
        Ok(Some(enc))
    } else {
        Err("当前平台不支持安全存储 token".into())
    }
}

fn clear_token(name: &str) {
    if cfg!(target_os = "macos") {
        let svc = format!("{KEYCHAIN_PREFIX}:{name}");
        let _ = std::process::Command::new("security")
            .args(["delete-generic-password", "-s", &svc])
            .output();
    }
}

// ---------------- claude 探测 ----------------
fn claude_found() -> bool {
    let names: &[&str] = if cfg!(target_os = "windows") {
        &["claude.exe", "claude.cmd", "claude.bat", "claude"]
    } else {
        &["claude"]
    };
    // 1. 进程继承到的 PATH（GUI 从资源管理器启动时可能拿到登录前的旧 PATH，
    //    即使用户后来才装 claude 并写入了 PATH，这里也查不到）。
    if let Ok(path) = std::env::var("PATH") {
        for dir in std::env::split_paths(&path) {
            for n in names {
                if dir.join(n).is_file() {
                    return true;
                }
            }
        }
    }
    // 2. 兜底：直接查默认安装位置，避免被陈旧的继承 PATH 误导。
    let h = home();
    let candidates: Vec<PathBuf> = if cfg!(target_os = "windows") {
        let mut v = vec![h.join(".local").join("bin")]; // native 安装器默认位置
        if let Ok(appdata) = std::env::var("APPDATA") {
            v.push(PathBuf::from(appdata).join("npm")); // npm -g 全局安装
        }
        v
    } else {
        vec![
            h.join(".local").join("bin"), // native 安装器默认位置
            h.join(".npm-global").join("bin"), // npm -g 全局安装
        ]
    };
    for dir in candidates {
        for n in names {
            if dir.join(n).is_file() {
                return true;
            }
        }
    }
    false
}

// ---------------- 命令 ----------------
#[tauri::command]
fn list_profiles() -> Vec<Profile> {
    load()
}

#[tauri::command]
fn save_profile(profile: Profile, token: Option<String>) -> Result<String, String> {
    let list = load();
    let mut p = profile;
    if p.type_ == "router" {
        match token.as_ref().filter(|s| !s.is_empty()) {
            Some(t) => match store_token(&p.name, t) {
                Ok(enc) => {
                    p.token_enc = enc;
                    p.has_token = true;
                }
                Err(e) => return Err(format!("保存 token 失败：{e}")),
            },
            None => {
                if let Some(old) = list.iter().find(|x| x.name == p.name) {
                    p.token_enc = old.token_enc.clone();
                    p.has_token = old.has_token;
                }
            }
        }
    } else {
        p.base_url = String::new();
        p.token_enc = None;
        p.opus_model = String::new();
        p.sonnet_model = String::new();
        p.haiku_model = String::new();
    }

    let mut list = list;
    if let Some(idx) = list.iter().position(|x| x.name == p.name) {
        list[idx] = p;
    } else {
        list.push(p);
    }
    save(&list).map_err(|e| e.to_string())?;
    install_integration(&list)
}

#[tauri::command]
fn delete_profile(name: String) -> Result<(), String> {
    let mut list = load();
    list.retain(|x| x.name != name);
    clear_token(&name);
    save(&list).map_err(|e| e.to_string())?;
    install_integration(&list)?;
    Ok(())
}

#[tauri::command]
fn sync_links(name: String, skills: bool, plugins: bool) -> Result<String, String> {
    let real_claude = home().join(".claude");
    let dest_claude = home().join(".claude-split").join(&name).join(".claude");
    let mut subs: Vec<&str> = vec![];
    if skills {
        subs.push("skills");
    }
    if plugins {
        subs.push("plugins");
    }
    if subs.is_empty() {
        return Ok("请先打开要共享的 skills 或 plugins 开关。".into());
    }

    if cfg!(target_os = "windows") {
        let dest = dest_claude.display().to_string();
        let src = real_claude.display().to_string();
        let mut lines = vec![format!(
            "New-Item -ItemType Directory -Force -Path '{dest}' | Out-Null"
        )];
        for sub in &subs {
            // 目录联结 Junction：普通权限即可，无需管理员、不弹 UAC
            lines.push(format!(
                "if (Test-Path '{src}\\{sub}') {{ if (Test-Path '{dest}\\{sub}') {{ cmd /c rmdir '{dest}\\{sub}' 2>$null }}; New-Item -ItemType Junction -Path '{dest}\\{sub}' -Target '{src}\\{sub}' | Out-Null }}"
            ));
        }
        let inner = lines.join("; ");
        let out = ps_command()
            .args(["-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", &inner])
            .output()
            .map_err(|e| e.to_string())?;
        if out.status.success() {
            Ok("已共享 skills/plugins（目录联结，无需管理员）。".into())
        } else {
            Err(String::from_utf8_lossy(&out.stderr).trim().to_string())
        }
    } else {
        fs::create_dir_all(&dest_claude).map_err(|e| e.to_string())?;
        let mut out: Vec<String> = vec![];
        for sub in &subs {
            let src = real_claude.join(sub);
            let dst = dest_claude.join(sub);
            if !src.exists() {
                out.push(format!("{sub}（主账户无此目录，跳过）"));
                continue;
            }
            if let Ok(meta) = fs::symlink_metadata(&dst) {
                if meta.file_type().is_symlink() {
                    let _ = fs::remove_file(&dst);
                } else {
                    out.push(format!("{sub}（目标已存在且非链接，跳过）"));
                    continue;
                }
            }
            #[cfg(unix)]
            {
                use std::os::unix::fs::symlink;
                match symlink(&src, &dst) {
                    Ok(_) => out.push(format!("{sub} ✓")),
                    Err(e) => out.push(format!("{sub} 失败：{e}")),
                }
            }
            #[cfg(not(unix))]
            {
                out.push(format!("{sub}（当前平台不支持）"));
            }
        }
        Ok(out.join(" | "))
    }
}

#[tauri::command]
fn environment() -> EnvInfo {
    let platform = if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "windows") {
        "windows"
    } else {
        "other"
    }
    .to_string();
    EnvInfo {
        platform,
        claude_found: claude_found(),
        integrated: cfg_path().exists(),
        cert_imported: cert_path().exists(),
        cert_count: count_certs(),
    }
}

// 统计信任库里已有几张证书（按 PEM 块计数）
fn count_certs() -> usize {
    fs::read_to_string(cert_path())
        .map(|s| s.matches("-----BEGIN CERTIFICATE-----").count())
        .unwrap_or(0)
}

// 导入 CA 证书：去重追加到固定 bundle 文件，并刷新集成脚本（脚本顶部会设置 NODE_EXTRA_CA_CERTS）
// 一个文件可放多张 PEM 证书，Node 会全部信任，故不同网关的不同证书都能共存、所有实例通用。
#[tauri::command]
fn import_cert(path: String) -> Result<String, String> {
    let src = PathBuf::from(path.trim());
    if !src.exists() {
        return Err("证书文件不存在，请确认路径。".into());
    }
    let new_cert = fs::read_to_string(&src).map_err(|e| format!("读取证书失败：{e}"))?;
    if !new_cert.contains("-----BEGIN CERTIFICATE-----") {
        return Err("文件里没找到 PEM 证书（缺 -----BEGIN CERTIFICATE-----）。".into());
    }
    fs::create_dir_all(cfg_dir()).map_err(|e| e.to_string())?;
    let dest = cert_path();
    let existing = fs::read_to_string(&dest).unwrap_or_default();
    // 去重：按"去掉所有换行"后的整段文本比对，已存在则跳过
    let norm = |s: &str| s.replace(['\r', '\n'], "");
    if norm(&existing).contains(&norm(&new_cert)) {
        return Ok(format!(
            "该证书已在信任库中（当前共 {} 张），无需重复导入。",
            count_certs()
        ));
    }
    let sep = if existing.is_empty() || existing.ends_with('\n') {
        ""
    } else {
        "\n"
    };
    let mut to_write = format!("{existing}{sep}{new_cert}");
    if !to_write.ends_with('\n') {
        to_write.push('\n');
    }
    fs::write(&dest, to_write).map_err(|e| format!("写入证书失败：{e}"))?;
    // 重新生成集成脚本，使其包含 NODE_EXTRA_CA_CERTS
    let list = load();
    let _ = install_integration(&list);
    Ok(format!(
        "证书已导入（累计 {} 张）。请重开终端后生效。",
        count_certs()
    ))
}

// 清空所有 CA 证书
#[tauri::command]
fn clear_certs() -> Result<String, String> {
    let p = cert_path();
    if p.exists() {
        fs::remove_file(&p).map_err(|e| format!("删除证书失败：{e}"))?;
    }
    let list = load();
    let _ = install_integration(&list);
    Ok("已清空所有 CA 证书。请重开终端后生效。".into())
}

// 检测网关可用模型：请求 {base_url}/v1/models
#[tauri::command]
fn detect_models(base_url: String, token: String) -> Result<Vec<String>, String> {
    let base = base_url.trim().trim_end_matches('/');
    if base.is_empty() {
        return Err("请先填写网关地址。".into());
    }
    if token.trim().is_empty() {
        return Err("请先填写 API Key（检测需要鉴权）。".into());
    }
    let url = format!("{base}/v1/models");
    let curl = if cfg!(target_os = "windows") {
        "curl.exe"
    } else {
        "curl"
    };
    let mut cmd = std::process::Command::new(curl);
    #[cfg(target_os = "windows")]
    {
        use std::os::windows::process::CommandExt;
        cmd.creation_flags(0x08000000);
    }
    cmd.arg("-s");
    // 检测仅读取模型列表、不传输敏感数据；跳过证书校验，避免证书不匹配导致无输出
    cmd.arg("-k");
    cmd.arg("-H")
        .arg(format!("Authorization: Bearer {}", token.trim()));
    cmd.arg(&url);
    let out = cmd.output().map_err(|e| format!("调用 curl 失败：{e}"))?;
    let body = String::from_utf8_lossy(&out.stdout).to_string();
    if body.trim().is_empty() {
        let err = String::from_utf8_lossy(&out.stderr);
        return Err(format!("无返回内容。可能是证书或网络问题：{}", err.trim()));
    }
    let v: serde_json::Value = serde_json::from_str(&body)
        .map_err(|_| format!("返回不是有效 JSON：{}", body.chars().take(160).collect::<String>()))?;
    let mut ids = vec![];
    if let Some(arr) = v.get("data").and_then(|d| d.as_array()) {
        for m in arr {
            if let Some(id) = m.get("id").and_then(|i| i.as_str()) {
                ids.push(id.to_string());
            }
        }
    }
    if ids.is_empty() {
        return Err(format!(
            "未解析到模型列表：{}",
            body.chars().take(160).collect::<String>()
        ));
    }
    Ok(ids)
}

// ---------------- 解密已存 key / 按实例检测模型 ----------------
fn decrypt_token(p: &Profile) -> Result<String, String> {
    if cfg!(target_os = "macos") {
        let svc = format!("{KEYCHAIN_PREFIX}:{}", p.name);
        let out = std::process::Command::new("security")
            .args(["find-generic-password", "-s", &svc, "-w"])
            .output()
            .map_err(|e| e.to_string())?;
        if !out.status.success() {
            return Err("未在钥匙串找到该实例的 Key".into());
        }
        Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
    } else if cfg!(target_os = "windows") {
        let enc = match &p.token_enc {
            Some(e) if !e.is_empty() => e.clone(),
            _ => return Err("该实例没有保存 Key".into()),
        };
        let escaped = enc.replace('\'', "''");
        let script = format!(
            "$sec=ConvertTo-SecureString '{escaped}'; $b=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec); [Runtime.InteropServices.Marshal]::PtrToStringBSTR($b)"
        );
        let out = ps_command()
            .args(["-NoProfile", "-Command", &script])
            .output()
            .map_err(|e| e.to_string())?;
        let tok = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if tok.is_empty() {
            return Err("解密 Key 失败".into());
        }
        Ok(tok)
    } else {
        Err("当前平台不支持".into())
    }
}

#[tauri::command]
fn detect_models_for(name: String) -> Result<Vec<String>, String> {
    let list = load();
    let p = list
        .iter()
        .find(|x| x.name == name)
        .ok_or_else(|| "未找到该实例".to_string())?;
    if p.type_ != "router" {
        return Err("该实例不是自定义路由，没有可检测的网关".into());
    }
    if p.base_url.is_empty() {
        return Err("该实例未配置网关地址".into());
    }
    let token = decrypt_token(p)?;
    detect_models(p.base_url.clone(), token)
}

// ---------------- 用量统计 ----------------
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct UsageRow {
    datetime: String,
    model: String,
    profile: String,
    input: u64,
    output: u64,
    cache_read: u64,
    cache_create: u64,
    requests: u64,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ConvRow {
    datetime: String,
    profile: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct UsageStats {
    daily: Vec<UsageRow>,
    conversations: Vec<ConvRow>,
    total_input: u64,
    total_output: u64,
    total_requests: u64,
    total_conversations: u64,
}

fn collect_jsonl(dir: &PathBuf, out: &mut Vec<PathBuf>) {
    if let Ok(rd) = fs::read_dir(dir) {
        for e in rd.flatten() {
            let p = e.path();
            if p.is_dir() {
                collect_jsonl(&p, out);
            } else if p.extension().and_then(|x| x.to_str()) == Some("jsonl") {
                out.push(p);
            }
        }
    }
}

#[tauri::command]
fn usage_stats() -> UsageStats {
    use std::collections::HashMap;
    let split = home().join(".claude-split");
    let mut map: HashMap<(String, String, String), UsageRow> = HashMap::new();
    let mut conv: Vec<ConvRow> = Vec::new();
    let mut total_input = 0u64;
    let mut total_output = 0u64;
    let mut total_requests = 0u64;
    let mut total_conversations = 0u64;

    if let Ok(insts) = fs::read_dir(&split) {
        for inst in insts.flatten() {
            if !inst.path().is_dir() {
                continue;
            }
            let profile = inst.file_name().to_string_lossy().to_string();
            let projects = inst.path().join(".claude").join("projects");
            let mut files = vec![];
            collect_jsonl(&projects, &mut files);
            for f in files {
                let content = match fs::read_to_string(&f) {
                    Ok(c) => c,
                    Err(_) => continue,
                };
                for line in content.lines() {
                    let has_usage = line.contains("\"usage\"");
                    // 用户真实提问：type=user 且不是工具返回（tool_result）
                    let maybe_user = line.contains("\"user\"") && !line.contains("tool_result");
                    if !has_usage && !maybe_user {
                        continue;
                    }
                    let v: serde_json::Value = match serde_json::from_str(line) {
                        Ok(x) => x,
                        Err(_) => continue,
                    };
                    let typ = v.get("type").and_then(|t| t.as_str()).unwrap_or("");

                    // —— 对话次数：统计用户真实提问 ——
                    if typ == "user" {
                        let is_tool = v
                            .get("message")
                            .and_then(|m| m.get("content"))
                            .map(|c| c.to_string().contains("tool_result"))
                            .unwrap_or(false);
                        if is_tool {
                            continue;
                        }
                        let ts = v.get("timestamp").and_then(|t| t.as_str()).unwrap_or("");
                        if ts.len() < 13 {
                            continue;
                        }
                        conv.push(ConvRow {
                            datetime: ts[..13].to_string(),
                            profile: profile.clone(),
                        });
                        total_conversations += 1;
                        continue;
                    }

                    // —— API 调用次数 + token：统计 assistant 消息 ——
                    if typ != "assistant" {
                        continue;
                    }
                    let msg = match v.get("message") {
                        Some(m) => m,
                        None => continue,
                    };
                    let model = msg.get("model").and_then(|m| m.as_str()).unwrap_or("");
                    if model.is_empty() || model == "<synthetic>" {
                        continue;
                    }
                    let usage = match msg.get("usage") {
                        Some(u) => u,
                        None => continue,
                    };
                    let gi = |k: &str| usage.get(k).and_then(|x| x.as_u64()).unwrap_or(0);
                    let input = gi("input_tokens");
                    let output = gi("output_tokens");
                    let cache_read = gi("cache_read_input_tokens");
                    let cache_create = gi("cache_creation_input_tokens");
                    if input + output + cache_read + cache_create == 0 {
                        continue;
                    }
                    let ts = v.get("timestamp").and_then(|t| t.as_str()).unwrap_or("");
                    if ts.len() < 13 {
                        continue;
                    }
                    let datetime = ts[..13].to_string(); // 例如 2026-06-22T04
                    let key = (datetime.clone(), model.to_string(), profile.clone());
                    let row = map.entry(key).or_insert(UsageRow {
                        datetime,
                        model: model.to_string(),
                        profile: profile.clone(),
                        input: 0,
                        output: 0,
                        cache_read: 0,
                        cache_create: 0,
                        requests: 0,
                    });
                    row.input += input;
                    row.output += output;
                    row.cache_read += cache_read;
                    row.cache_create += cache_create;
                    row.requests += 1;
                    total_input += input;
                    total_output += output;
                    total_requests += 1;
                }
            }
        }
    }

    let mut daily: Vec<UsageRow> = map.into_values().collect();
    daily.sort_by(|a, b| a.datetime.cmp(&b.datetime));
    UsageStats {
        daily,
        conversations: conv,
        total_input,
        total_output,
        total_requests,
        total_conversations,
    }
}

fn main() {
    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .invoke_handler(tauri::generate_handler![
            list_profiles,
            save_profile,
            delete_profile,
            sync_links,
            environment,
            import_cert,
            clear_certs,
            detect_models,
            detect_models_for,
            usage_stats
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
